server:
  port: 8086

app:
  security:
    api-key: ${API_KEY_NOTIFICATIONS:dev-secret}
  mail:
    from: ${MAIL_FROM:oscarmayor0211@gmail.com}

spring:
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:oscarmayor0211@gmail.com}   # tu cuenta @gmail.com
    password: ${MAIL_PASSWORD:okgp wuhn qrzy lduf}   # App password (16 chars)
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.connectiontimeout: 5000
      mail.smtp.timeout: 5000
      mail.smtp.writetimeout: 5000
